### ISSUE TITLE
Is the demo page supposed to be in a working state?

### ISSUE THREAD

**Issue by Kuratius** [dhvcc/booklette#1]
See title

**Comment by dhvcc** [comment]
Nope, it's still very much WIP, just getting to know flutter. Although. You can technically read EPUBs off of it (after current commit is deployed) it's lacking state persistance, firebase integration and basic quality of life features, I need to update the README, just didn't get to do it since it's a very new project :)

**Comment by dhvcc** [comment]
Updated the readme, hopefully this clears out the confusion
Anyways, thanks for having an interest in the project, closing for now
